language: python
python:
    - "3.8"

install:
  - python -m pip install -U pip
  - python setup.py install

script:
  - pylint department-app/tests
  - coverage run setup.py --help-commands
after-success:
  - coveralls

notifications:
  - email:
      on_success: never
      on_failure: always
