language: python
python:
  - '3.8'

install:
  - pip install wheel -U setuptools -U pip mypy flake8

jobs:
  include:
    - stage: build
      script: python setup.py
    - stage: ci
      script: make ci

after_success:
  - make test-coverage