os: linux
dist: focal

language: python
python:
- '3.8'
env:
  - DOCKER_COMPOSE_VERSION=1.28.2
services:
  - docker

addons:
  apt:
    packages:
      - make

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin

jobs:
  include:
    - stage: build
      script:
        - make build
        - docker push ljte/lab-project:latest
    - stage: ci
      script:
        - docker pull ljte/lab-project:latest
        - make ci
    - stage: deploy
        script: skip
        deploy:
          provider: heroku
          api_key: $HEROKU_API_KEY
          on:
            branch: master
          run:
            - make run
