language: python
python:
  - '3.8'

install:
  - pip install wheel -U setuptools -U pip mypy flake8

jobs:
  include:
    - stage: ci
      script:
        - make build
        - make ci

after_success:
  - make test-coverage