language: python
python:
  - "3.8"

install:
  - python -m pip install -U pip
  - python setup.py install

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER user_1 WITH PASSWORD '12345';" -U postgres
  - psql -c "ALTER USER user_1 WITH Superuser Createrole Createdb;" -U postgres
  - psql -c "\c test" -U postgres
  - psql -c "create table department (id integer PRIMARY KEY, name varchar(255) NOT NULL);"
  - psql -c "\dt" -U postgres
  - gunicorn "run:run()" &

script:
  - pylint department_app/
  - coverage run setup.py test

after-success:
  - coveralls

notifications:
  - email:
      recipients:
        - ljte823@gmail.com
      on_success: never
      on_failure: always
