language: python
python:
  - "3.8"

install:
  - python -m pip install -U pip
  - python setup.py install

script:
  - pylint department-app/tests
  - coverage run setup.py test
after-success:
  - coveralls

notifications:
  - email:
      recipients:
        - ljte823@gmail.com
      on_success: never
      on_failure: always
