language: python
python:
    - "3.8"

install: python setup.py install

script:
  - pylint department-app/tests
  - coverage run department-app/tests
after-success:
  - coveralls

notifications:
  - email:
      on_success: never
      on_failure: always
