language: python
python:
  - '3.8'

install:
  - pip install wheel -U setuptools -U pip mypy flake8

before_script:
  - make format-check
  - make mypy-check

script:
  - make build
  - make tests

after_success:
  - make test-coverage