language: python
python:
  - "3.8"

install:
  - python -m pip install -U pip
  - python setup.py install

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres

script:
  - pylint --disable=no-self-use,too-few-public-methods,no-member,broad-except,too-many-public-methods --max-line-length=120 department_app/
  - coverage run setup.py test

after-success:
  - coveralls

deploy:
  provider: heroku
  api_key:
    secure: cqWCwU06dlZKjkwNPJ4sjdC5ig6DdfBpKvApWmuEx3EFJ5Vf5jK33M8yXiXrtxSvRQdPZtP+f3UglaxYOMGXHKLj1BiBHRxqvuDjvc87B0De/K2UioVIW/ZrV/BHaAjKnyaFrfwIL+WRZrBBR0+h3SAb3xXmgsZbAf1l6ZBlUv8x7RRH6+ZA9uS64kvABufguWP8O06av7k//BkSs5JTi+K4FxJzyCvrxW5X/xRO5gmKqK22AJedckjBN+uSaGQEkML2Tsr0DPjbqwjJWlHR/F02bFu/r/OhEoTrmNWWDaSdMGtjnU438sCKaIyCF5JckkPe2Rs4PTvDBWA/k7V3isRj63ZZgbZFUdg8xYCA1IQMzIigNIvQIdlDS2B9/RZLbauph6DSKxBo4B3438w4f6JBFd7LdHnAzDxZiEViI+fRK3KI4rEGVzwIc1L4h7MinWasoC/PMrpMC7OLoPhh0cDlGKoetvX5wmCgul/KRuKR102c7y8urse8MDTNb5fo1TH69ztHmfaS4+K22l49tDQDsGQLvOMl2E4teFhrm2mzO9e1SHUNVZL7t+zrwXTSaYVvXNEDuUzoDLeJfIM/MyWVscdBteNdCtpHEElbJ38g4r/mJnbxp9IefhEj3qyw2xtonHonyQfXD8263bUGVhBLb0/CfzCrp7pgdtSDH0M=
  strategy: git

notifications:
  - email:
      recipients:
        - ljte823@gmail.com
      on_success: never
      on_failure: always
