services:
  app:
    image: ljte/lab-project
    build:
      context: .
      dockerfile: etc/app/Dockerfile
    env_file: etc/app/env/dev.env
    environment:
      - SECRET_KEY=$SECRET_KEY
    depends_on:
      postgres:
          condition: service_healthy
    volumes:
      - ./department_app:/app
      - ./department_app/static:/app/static
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/healthcheck/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - lab_project_network


  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lab_project_network

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./department_app/static/:/media/static/
    networks:
      - lab_project_network
    depends_on:
      - app

networks:
  lab_project_network:
    external: true
