services:
  app:
    image: ljte/lab-project
    build:
      context: .
      dockerfile: ./etc/Dockerfile
    env_file: ./etc/env/dev.env
    environment:
      - SECRET_KEY=$SECRET_KEY
    depends_on:
      postgres:
          condition: service_healthy
    volumes:
      - ./department_app:/app
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/healthcheck/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
